Correcting and improving translation
ESX-PUBLIC/esx_hacking pull request #2
Opened 2020-01-07 01:03 UTC by maiconkkl

2020-01-15 20:02 UTC, ElPumpo requested changes

2020-01-15 20:02 UTC, ElPumpo commented on locales/br.lua
> +}
trailing missing

2020-01-15 21:55 UTC, maiconkkl reviewed
fixed

2020-01-15 21:55 UTC, maiconkkl commented on locales/br.lua
> +}
fixed

2020-01-16 19:23 UTC, kibonara commented
requests added, thanks for ur help

2020-01-16 19:47 UTC, closed without merging

2020-01-16 19:47 UTC, ElPumpo commented
@kibonara that's NOT how you accept a pull request?!